# Site settings
title: Jimmy's Blog
name: Jimmy Bengtsson
email: jb223pu@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Studying the Web Development Programme at Linnaeus University.
  On this blog I will post things related to my studies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jimmybengtsson.github.io" # the base hostname & protocol for your site
github:  jimmybengtsson
facebook: krewcifix

pic: https://avatars0.githubusercontent.com/u/21309450?v=3&s=400

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: "<!–-break-–>"
